-- Seed companies from the UIT internship partner sheet shared by the user.
-- Run this after supabase-schema.sql. Admin can refine details later from /admin.

insert into public.companies (
  id,
  name,
  description,
  industry,
  location,
  size,
  working_hours,
  majors,
  roles,
  facilities,
  intern_duration,
  stipend,
  rating,
  total_reviews,
  logo,
  featured,
  active
)
values
  (
    'nscs',
    'NSCS',
    'Internship partner listed in the UIT previous-year company intake sheet. Admins can refine details after confirming company information.',
    'Technology & Internship Partner',
    'Myanmar',
    'To be confirmed',
    'To be confirmed',
    '["SE"]'::jsonb,
    '["Intern"]'::jsonb,
    '["UIT internship partner"]'::jsonb,
    'To be confirmed',
    'To be confirmed',
    0,
    25,
    'building',
    true,
    true
  ),
  (
    'maruichi-warehouse-japan',
    'Maruichi Warehouse Japan Company',
    'Internship partner listed in the UIT previous-year company intake sheet. Admins can refine details after confirming company information.',
    'Logistics & Technology',
    'Japan',
    'To be confirmed',
    'To be confirmed',
    '["SE"]'::jsonb,
    '["Intern"]'::jsonb,
    '["Japan internship partner"]'::jsonb,
    'To be confirmed',
    'To be confirmed',
    0,
    4,
    'briefcase',
    false,
    true
  ),
  (
    'ucs-myanmar',
    'UCS Myanmar',
    'Internship partner listed in the UIT previous-year company intake sheet. Admins can refine details after confirming company information.',
    'Software & IT Services',
    'Myanmar',
    'To be confirmed',
    'To be confirmed',
    '["SE"]'::jsonb,
    '["Software Intern"]'::jsonb,
    '["UIT internship partner"]'::jsonb,
    'To be confirmed',
    'To be confirmed',
    0,
    4,
    'building',
    false,
    true
  ),
  (
    'zmken-service-fukuoka',
    'Zm''ken Service Co., Ltd. Fukuoka, Japan',
    'Internship partner listed in the UIT previous-year company intake sheet. Admins can refine details after confirming company information.',
    'Software & IT Services',
    'Fukuoka, Japan',
    'To be confirmed',
    'To be confirmed',
    '["SE"]'::jsonb,
    '["Software Intern"]'::jsonb,
    '["Japan internship partner"]'::jsonb,
    'To be confirmed',
    'To be confirmed',
    0,
    3,
    'building',
    false,
    true
  ),
  (
    'cyber-innovation-aots',
    'Cyber Innovation (AOTS)',
    'Internship partner listed in the UIT previous-year company intake sheet. Admins can refine details after confirming company information.',
    'Cybersecurity & Technology',
    'To be confirmed',
    'To be confirmed',
    'To be confirmed',
    '["CS"]'::jsonb,
    '["Cybersecurity Intern"]'::jsonb,
    '["UIT internship partner"]'::jsonb,
    'To be confirmed',
    'To be confirmed',
    0,
    1,
    'shield',
    false,
    true
  ),
  (
    'aya',
    'AYA',
    'Internship partner listed in the UIT previous-year company intake sheet. Admins can refine details after confirming company information.',
    'Banking & Digital Services',
    'Myanmar',
    'To be confirmed',
    'To be confirmed',
    '["SE"]'::jsonb,
    '["Software Intern", "Digital Services Intern"]'::jsonb,
    '["UIT internship partner"]'::jsonb,
    'To be confirmed',
    'To be confirmed',
    0,
    17,
    'briefcase',
    true,
    true
  ),
  (
    'nex4',
    'Nex4',
    'Internship partner listed in the UIT previous-year company intake sheet. Admins can refine details after confirming company information.',
    'Technology & IT Services',
    'Myanmar',
    'To be confirmed',
    'To be confirmed',
    '["HPC", "CS"]'::jsonb,
    '["Intern"]'::jsonb,
    '["UIT internship partner"]'::jsonb,
    'To be confirmed',
    'To be confirmed',
    0,
    5,
    'globe',
    false,
    true
  ),
  (
    'keisuigiken-corporation',
    'KEISUIGIKEN Corporation',
    'Internship partner listed in the UIT previous-year company intake sheet. Admins can refine details after confirming company information.',
    'Technology & Engineering',
    'Japan',
    'To be confirmed',
    'To be confirmed',
    '["KE"]'::jsonb,
    '["Intern"]'::jsonb,
    '["Japan internship partner"]'::jsonb,
    'To be confirmed',
    'To be confirmed',
    0,
    3,
    'building',
    false,
    true
  ),
  (
    'wave-money',
    'Wave Money',
    'Myanmar mobile financial services company listed in the UIT previous-year internship intake sheet.',
    'FinTech',
    'Myanmar',
    'To be confirmed',
    'To be confirmed',
    '["SE"]'::jsonb,
    '["Software Intern", "FinTech Intern"]'::jsonb,
    '["UIT internship partner"]'::jsonb,
    'To be confirmed',
    'To be confirmed',
    0,
    10,
    'wallet',
    true,
    true
  ),
  (
    'bim-group',
    'BIM Group',
    'Internship partner listed in the UIT previous-year company intake sheet. Admins can refine details after confirming company information.',
    'Business & Technology',
    'Myanmar',
    'To be confirmed',
    'To be confirmed',
    '["KE", "CN"]'::jsonb,
    '["Intern"]'::jsonb,
    '["UIT internship partner"]'::jsonb,
    'To be confirmed',
    'To be confirmed',
    0,
    20,
    'briefcase',
    true,
    true
  ),
  (
    'upg',
    'UPG',
    'Internship partner listed in the UIT previous-year company intake sheet. Admins can refine details after confirming company information.',
    'Technology & Internship Partner',
    'Myanmar',
    'To be confirmed',
    'To be confirmed',
    '["BIS", "SE", "CN"]'::jsonb,
    '["Intern"]'::jsonb,
    '["UIT internship partner"]'::jsonb,
    'To be confirmed',
    'To be confirmed',
    0,
    2,
    'building',
    false,
    true
  ),
  (
    'dir-ace-technology',
    'DIR-ACE Technology',
    'Internship partner listed in the UIT previous-year company intake sheet. Admins can refine details after confirming company information.',
    'Technology & IT Services',
    'Myanmar',
    'To be confirmed',
    'To be confirmed',
    '["BIS", "SE", "CN", "ES"]'::jsonb,
    '["Technology Intern"]'::jsonb,
    '["UIT internship partner"]'::jsonb,
    'To be confirmed',
    'To be confirmed',
    0,
    10,
    'building',
    false,
    true
  ),
  (
    'kddi',
    'KDDI',
    'Internship partner listed in the UIT previous-year company intake sheet. Admins can refine details after confirming company information.',
    'Telecommunications & Technology',
    'Japan / Myanmar',
    'To be confirmed',
    'To be confirmed',
    '["BIS", "HPC", "SE", "CN", "CS"]'::jsonb,
    '["Technology Intern"]'::jsonb,
    '["International internship partner"]'::jsonb,
    'To be confirmed',
    'To be confirmed',
    0,
    4,
    'signal',
    false,
    true
  ),
  (
    'gic',
    'GIC',
    'Internship partner listed in the UIT previous-year company intake sheet. Admins can refine details after confirming company information.',
    'Technology & Internship Partner',
    'Myanmar',
    'To be confirmed',
    'To be confirmed',
    '["SE"]'::jsonb,
    '["Intern"]'::jsonb,
    '["UIT internship partner"]'::jsonb,
    'To be confirmed',
    'To be confirmed',
    0,
    50,
    'building',
    true,
    true
  ),
  (
    'care-viewer',
    'Care Viewer',
    'Internship partner listed in the UIT previous-year company intake sheet. Admins can refine details after confirming company information.',
    'Health Technology',
    'To be confirmed',
    'To be confirmed',
    'To be confirmed',
    '["SE"]'::jsonb,
    '["Software Intern"]'::jsonb,
    '["UIT internship partner"]'::jsonb,
    'To be confirmed',
    'To be confirmed',
    0,
    3,
    'mobile',
    false,
    true
  ),
  (
    'signal-base',
    'Signal Base',
    'Internship partner listed in the UIT previous-year company intake sheet. Admins can refine details after confirming company information.',
    'Technology & IT Services',
    'To be confirmed',
    'To be confirmed',
    'To be confirmed',
    '["SE"]'::jsonb,
    '["Software Intern"]'::jsonb,
    '["UIT internship partner"]'::jsonb,
    'To be confirmed',
    'To be confirmed',
    0,
    4,
    'signal',
    false,
    true
  ),
  (
    'city-holdings-group',
    'City Holdings Group',
    'Internship partner listed in the UIT previous-year company intake sheet. Admins can refine details after confirming company information.',
    'Business & Digital Services',
    'Myanmar',
    'To be confirmed',
    'To be confirmed',
    '["SE"]'::jsonb,
    '["Technology Intern"]'::jsonb,
    '["UIT internship partner"]'::jsonb,
    'To be confirmed',
    'To be confirmed',
    0,
    6,
    'briefcase',
    false,
    true
  ),
  (
    'xypha-tech',
    'XYPHA Tech',
    'Internship partner listed in the UIT previous-year company intake sheet. Admins can refine details after confirming company information.',
    'Technology & IT Services',
    'Myanmar',
    'To be confirmed',
    'To be confirmed',
    '["SE"]'::jsonb,
    '["Software Intern"]'::jsonb,
    '["UIT internship partner"]'::jsonb,
    'To be confirmed',
    'To be confirmed',
    0,
    2,
    'rocket',
    false,
    true
  ),
  (
    'ace',
    'ACE',
    'Internship partner listed in the UIT previous-year company intake sheet. Admins can refine details after confirming company information.',
    'Technology & Internship Partner',
    'Myanmar',
    'To be confirmed',
    'To be confirmed',
    '["SE"]'::jsonb,
    '["Intern"]'::jsonb,
    '["UIT internship partner"]'::jsonb,
    'To be confirmed',
    'To be confirmed',
    0,
    10,
    'building',
    false,
    true
  ),
  (
    'frontiir-net',
    'Frontiir.Net',
    'Internet and networking company listed in the UIT previous-year internship intake sheet.',
    'Internet & Networking',
    'Myanmar',
    'To be confirmed',
    'To be confirmed',
    '["BIS", "HPC", "KE", "SE"]'::jsonb,
    '["Network Intern", "Technology Intern"]'::jsonb,
    '["UIT internship partner"]'::jsonb,
    'To be confirmed',
    'To be confirmed',
    0,
    10,
    'globe',
    true,
    true
  ),
  (
    'sourcecode',
    'SourceCode',
    'Internship partner listed in the UIT previous-year company intake sheet with broad major eligibility.',
    'Software & IT Services',
    'Myanmar',
    'To be confirmed',
    'To be confirmed',
    '["BIS", "HPC", "KE", "SE", "CN", "ES", "CS"]'::jsonb,
    '["Software Intern", "Technology Intern"]'::jsonb,
    '["UIT internship partner"]'::jsonb,
    'To be confirmed',
    'To be confirmed',
    0,
    5,
    'mobile',
    false,
    true
  ),
  (
    'brillar-atenxion',
    'Brillar/Atenxion',
    'Internship partner listed in the UIT previous-year company intake sheet. Admins can refine details after confirming company information.',
    'Technology & IT Services',
    'To be confirmed',
    'To be confirmed',
    'To be confirmed',
    '["SE"]'::jsonb,
    '["Software Intern"]'::jsonb,
    '["UIT internship partner"]'::jsonb,
    'To be confirmed',
    'To be confirmed',
    0,
    15,
    'building',
    false,
    true
  ),
  (
    'kbzms',
    'KBZMS',
    'Internship partner listed in the UIT previous-year company intake sheet. Admins can refine details after confirming company information.',
    'Insurance & Digital Services',
    'Myanmar',
    'To be confirmed',
    'To be confirmed',
    '["SE"]'::jsonb,
    '["Technology Intern"]'::jsonb,
    '["UIT internship partner"]'::jsonb,
    'To be confirmed',
    'To be confirmed',
    0,
    0,
    'briefcase',
    false,
    true
  ),
  (
    'anzer',
    'ANZER',
    'Internship partner listed in the UIT previous-year company intake sheet. Admins can refine details after confirming company information.',
    'Technology & IT Services',
    'To be confirmed',
    'To be confirmed',
    'To be confirmed',
    '["SE"]'::jsonb,
    '["Technology Intern"]'::jsonb,
    '["UIT internship partner"]'::jsonb,
    'To be confirmed',
    'To be confirmed',
    0,
    0,
    'building',
    false,
    true
  )
on conflict (id) do update
set
  name = excluded.name,
  description = excluded.description,
  industry = excluded.industry,
  location = excluded.location,
  size = excluded.size,
  working_hours = excluded.working_hours,
  majors = excluded.majors,
  roles = excluded.roles,
  facilities = excluded.facilities,
  intern_duration = excluded.intern_duration,
  stipend = excluded.stipend,
  rating = excluded.rating,
  total_reviews = excluded.total_reviews,
  logo = excluded.logo,
  featured = excluded.featured,
  active = excluded.active,
  updated_at = now();
